# Generated by Django 5.1.1 on 2024-10-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_alter_buyer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task1.buyer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task1.game')),
            ],
        ),
    ]
